//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOS_PICKING_LOG
    {
        public int COD_MOVIMIENTO_LOG { get; set; }
        public Nullable<int> COD_PETICION { get; set; }
        public Nullable<int> COD_PALET { get; set; }
        public Nullable<System.DateTime> FECH_REALIZACION { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string UBICACION { get; set; }
    
        public virtual ORDEN_SALIDA_CAB ORDEN_SALIDA_CAB { get; set; }
        public virtual PALETS PALETS { get; set; }
        public virtual UBICACIONES UBICACIONES { get; set; }
    }
}
