//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCIONES_CAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECEPCIONES_CAB()
        {
            this.RECEPCIONES_LIN = new HashSet<RECEPCIONES_LIN>();
        }
    
        public int ALBARAN { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> ID_EMPRESA { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<System.DateTime> FECH_LLEGADA { get; set; }
    
        public virtual EMPRESAS EMPRESAS { get; set; }
        public virtual ESTADOS_RECEPCION ESTADOS_RECEPCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEPCIONES_LIN> RECEPCIONES_LIN { get; set; }
    }
}
