//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MOVIMIENTOS_PICKING
    {
        public int COD_MOVIMIENTO { get; set; }
        public Nullable<int> COD_PETICION { get; set; }
        public Nullable<int> COD_PALET { get; set; }
        public string COD_REFERENCIA { get; set; }
        public string DES_REFERENCIA { get; set; }
        public string UBICACION { get; set; }
        public string CALLE { get; set; }
        public string POSICION { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<bool> REALIZADO { get; set; }
    }
}
