//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ORDEN_SALIDA_INCIDENCIAS
    {
        public int ID_INCIDENCIA { get; set; }
        public string DES_INCIDENCIA { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> COD_PETICION { get; set; }
        public Nullable<int> ID_EMPRESA { get; set; }
        public string DIRECCION_ENTREGA { get; set; }
        public string COD_POSTAL { get; set; }
        public string POBLACION { get; set; }
    }
}
