//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDEntities : DbContext
    {
        public BDEntities()
            : base("name=BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPRESAS> EMPRESAS { get; set; }
        public virtual DbSet<ESTADOS_ORDEN_SALIDA> ESTADOS_ORDEN_SALIDA { get; set; }
        public virtual DbSet<ESTADOS_PALETS> ESTADOS_PALETS { get; set; }
        public virtual DbSet<ESTADOS_RECEPCION> ESTADOS_RECEPCION { get; set; }
        public virtual DbSet<MOVIMIENTOS_PICKING> MOVIMIENTOS_PICKING { get; set; }
        public virtual DbSet<MOVIMIENTOS_PICKING_LOG> MOVIMIENTOS_PICKING_LOG { get; set; }
        public virtual DbSet<ORDEN_SALIDA_CAB> ORDEN_SALIDA_CAB { get; set; }
        public virtual DbSet<ORDEN_SALIDA_INCIDENCIAS> ORDEN_SALIDA_INCIDENCIAS { get; set; }
        public virtual DbSet<ORDEN_SALIDA_LIN> ORDEN_SALIDA_LIN { get; set; }
        public virtual DbSet<PALETS> PALETS { get; set; }
        public virtual DbSet<RECEPCIONES_CAB> RECEPCIONES_CAB { get; set; }
        public virtual DbSet<RECEPCIONES_LIN> RECEPCIONES_LIN { get; set; }
        public virtual DbSet<REFERENCIAS> REFERENCIAS { get; set; }
        public virtual DbSet<UBICACIONES> UBICACIONES { get; set; }
        public virtual DbSet<V_MOVIMIENTOS_PICKING> V_MOVIMIENTOS_PICKING { get; set; }
        public virtual DbSet<V_ORDEN_SALIDA_CAB> V_ORDEN_SALIDA_CAB { get; set; }
        public virtual DbSet<V_ORDEN_SALIDA_INCIDENCIAS> V_ORDEN_SALIDA_INCIDENCIAS { get; set; }
        public virtual DbSet<V_ORDEN_SALIDA_LIN> V_ORDEN_SALIDA_LIN { get; set; }
        public virtual DbSet<V_PALETS> V_PALETS { get; set; }
        public virtual DbSet<V_RECEPCIONES_CAB> V_RECEPCIONES_CAB { get; set; }
        public virtual DbSet<V_RECEPCIONES_LIN> V_RECEPCIONES_LIN { get; set; }
        public virtual DbSet<V_REFERENCIAS> V_REFERENCIAS { get; set; }
    
        public virtual int PA_EMAIL_RECEPCIONES(string dESTINATARIOS, string aSUNTO_EMAIL, Nullable<int> aLBARAN, Nullable<int> iNVOKER, string uSUARIO, string cULTURA, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var dESTINATARIOSParameter = dESTINATARIOS != null ?
                new ObjectParameter("DESTINATARIOS", dESTINATARIOS) :
                new ObjectParameter("DESTINATARIOS", typeof(string));
    
            var aSUNTO_EMAILParameter = aSUNTO_EMAIL != null ?
                new ObjectParameter("ASUNTO_EMAIL", aSUNTO_EMAIL) :
                new ObjectParameter("ASUNTO_EMAIL", typeof(string));
    
            var aLBARANParameter = aLBARAN.HasValue ?
                new ObjectParameter("ALBARAN", aLBARAN) :
                new ObjectParameter("ALBARAN", typeof(int));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cULTURAParameter = cULTURA != null ?
                new ObjectParameter("CULTURA", cULTURA) :
                new ObjectParameter("CULTURA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_EMAIL_RECEPCIONES", dESTINATARIOSParameter, aSUNTO_EMAILParameter, aLBARANParameter, iNVOKERParameter, uSUARIOParameter, cULTURAParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_GENERAR_ETIQUETA(Nullable<int> cOD_PALET, Nullable<int> iNVOKER, string uSUARIO, string cULTURA, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var cOD_PALETParameter = cOD_PALET.HasValue ?
                new ObjectParameter("COD_PALET", cOD_PALET) :
                new ObjectParameter("COD_PALET", typeof(int));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cULTURAParameter = cULTURA != null ?
                new ObjectParameter("CULTURA", cULTURA) :
                new ObjectParameter("CULTURA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_GENERAR_ETIQUETA", cOD_PALETParameter, iNVOKERParameter, uSUARIOParameter, cULTURAParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_GESTIONAR_PALETS(Nullable<int> cOD_PALET, string cOD_UBICACION_NUEVA, Nullable<int> cOD_PALET_ABSORBIDO, Nullable<int> cANTIDAD_PARTIDA, Nullable<int> iNVOKER, string uSUARIO, string cULTURA, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var cOD_PALETParameter = cOD_PALET.HasValue ?
                new ObjectParameter("COD_PALET", cOD_PALET) :
                new ObjectParameter("COD_PALET", typeof(int));
    
            var cOD_UBICACION_NUEVAParameter = cOD_UBICACION_NUEVA != null ?
                new ObjectParameter("COD_UBICACION_NUEVA", cOD_UBICACION_NUEVA) :
                new ObjectParameter("COD_UBICACION_NUEVA", typeof(string));
    
            var cOD_PALET_ABSORBIDOParameter = cOD_PALET_ABSORBIDO.HasValue ?
                new ObjectParameter("COD_PALET_ABSORBIDO", cOD_PALET_ABSORBIDO) :
                new ObjectParameter("COD_PALET_ABSORBIDO", typeof(int));
    
            var cANTIDAD_PARTIDAParameter = cANTIDAD_PARTIDA.HasValue ?
                new ObjectParameter("CANTIDAD_PARTIDA", cANTIDAD_PARTIDA) :
                new ObjectParameter("CANTIDAD_PARTIDA", typeof(int));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cULTURAParameter = cULTURA != null ?
                new ObjectParameter("CULTURA", cULTURA) :
                new ObjectParameter("CULTURA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_GESTIONAR_PALETS", cOD_PALETParameter, cOD_UBICACION_NUEVAParameter, cOD_PALET_ABSORBIDOParameter, cANTIDAD_PARTIDAParameter, iNVOKERParameter, uSUARIOParameter, cULTURAParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_MOVIMIENTOS_PICKING(Nullable<int> cOD_PETICION, Nullable<int> cOD_LINEA, Nullable<int> cOD_MOVIMIENTO, Nullable<int> iNVOKER, string uSUARIO, string cULTURA, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var cOD_PETICIONParameter = cOD_PETICION.HasValue ?
                new ObjectParameter("COD_PETICION", cOD_PETICION) :
                new ObjectParameter("COD_PETICION", typeof(int));
    
            var cOD_LINEAParameter = cOD_LINEA.HasValue ?
                new ObjectParameter("COD_LINEA", cOD_LINEA) :
                new ObjectParameter("COD_LINEA", typeof(int));
    
            var cOD_MOVIMIENTOParameter = cOD_MOVIMIENTO.HasValue ?
                new ObjectParameter("COD_MOVIMIENTO", cOD_MOVIMIENTO) :
                new ObjectParameter("COD_MOVIMIENTO", typeof(int));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cULTURAParameter = cULTURA != null ?
                new ObjectParameter("CULTURA", cULTURA) :
                new ObjectParameter("CULTURA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOVIMIENTOS_PICKING", cOD_PETICIONParameter, cOD_LINEAParameter, cOD_MOVIMIENTOParameter, iNVOKERParameter, uSUARIOParameter, cULTURAParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_ORDEN_SALIDA_CAB(Nullable<int> cOD_PETICION, Nullable<int> eSTADO, Nullable<int> iD_EMPRESA, string dIRECCION_ENTREGA, string cOD_POSTAL, string pOBLACION, string pROVINCIA, string tELEFONO, Nullable<System.DateTime> fECH_CREACION, Nullable<int> iNVOKER, string uSUARIO, string cULTURA, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var cOD_PETICIONParameter = cOD_PETICION.HasValue ?
                new ObjectParameter("COD_PETICION", cOD_PETICION) :
                new ObjectParameter("COD_PETICION", typeof(int));
    
            var eSTADOParameter = eSTADO.HasValue ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(int));
    
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(int));
    
            var dIRECCION_ENTREGAParameter = dIRECCION_ENTREGA != null ?
                new ObjectParameter("DIRECCION_ENTREGA", dIRECCION_ENTREGA) :
                new ObjectParameter("DIRECCION_ENTREGA", typeof(string));
    
            var cOD_POSTALParameter = cOD_POSTAL != null ?
                new ObjectParameter("COD_POSTAL", cOD_POSTAL) :
                new ObjectParameter("COD_POSTAL", typeof(string));
    
            var pOBLACIONParameter = pOBLACION != null ?
                new ObjectParameter("POBLACION", pOBLACION) :
                new ObjectParameter("POBLACION", typeof(string));
    
            var pROVINCIAParameter = pROVINCIA != null ?
                new ObjectParameter("PROVINCIA", pROVINCIA) :
                new ObjectParameter("PROVINCIA", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var fECH_CREACIONParameter = fECH_CREACION.HasValue ?
                new ObjectParameter("FECH_CREACION", fECH_CREACION) :
                new ObjectParameter("FECH_CREACION", typeof(System.DateTime));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cULTURAParameter = cULTURA != null ?
                new ObjectParameter("CULTURA", cULTURA) :
                new ObjectParameter("CULTURA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_ORDEN_SALIDA_CAB", cOD_PETICIONParameter, eSTADOParameter, iD_EMPRESAParameter, dIRECCION_ENTREGAParameter, cOD_POSTALParameter, pOBLACIONParameter, pROVINCIAParameter, tELEFONOParameter, fECH_CREACIONParameter, iNVOKERParameter, uSUARIOParameter, cULTURAParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_ORDEN_SALIDA_INCIDENCIAS(Nullable<int> cOD_PETICION, string dESCRIPCION, Nullable<int> iNVOKER, string uSUARIO, string cULTURA, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var cOD_PETICIONParameter = cOD_PETICION.HasValue ?
                new ObjectParameter("COD_PETICION", cOD_PETICION) :
                new ObjectParameter("COD_PETICION", typeof(int));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cULTURAParameter = cULTURA != null ?
                new ObjectParameter("CULTURA", cULTURA) :
                new ObjectParameter("CULTURA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_ORDEN_SALIDA_INCIDENCIAS", cOD_PETICIONParameter, dESCRIPCIONParameter, iNVOKERParameter, uSUARIOParameter, cULTURAParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_ORDEN_SALIDA_LIN(Nullable<int> cOD_PETICION, Nullable<int> cOD_LINEA, string cOD_REFERENCIA, Nullable<int> cANTIDAD, Nullable<int> iNVOKER, string uSUARIO, string cULTURA, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var cOD_PETICIONParameter = cOD_PETICION.HasValue ?
                new ObjectParameter("COD_PETICION", cOD_PETICION) :
                new ObjectParameter("COD_PETICION", typeof(int));
    
            var cOD_LINEAParameter = cOD_LINEA.HasValue ?
                new ObjectParameter("COD_LINEA", cOD_LINEA) :
                new ObjectParameter("COD_LINEA", typeof(int));
    
            var cOD_REFERENCIAParameter = cOD_REFERENCIA != null ?
                new ObjectParameter("COD_REFERENCIA", cOD_REFERENCIA) :
                new ObjectParameter("COD_REFERENCIA", typeof(string));
    
            var cANTIDADParameter = cANTIDAD.HasValue ?
                new ObjectParameter("CANTIDAD", cANTIDAD) :
                new ObjectParameter("CANTIDAD", typeof(int));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cULTURAParameter = cULTURA != null ?
                new ObjectParameter("CULTURA", cULTURA) :
                new ObjectParameter("CULTURA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_ORDEN_SALIDA_LIN", cOD_PETICIONParameter, cOD_LINEAParameter, cOD_REFERENCIAParameter, cANTIDADParameter, iNVOKERParameter, uSUARIOParameter, cULTURAParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_PALETS(string cOD_REFERENCIA, Nullable<int> cOD_ESTADO, Nullable<int> cANTIDAD, Nullable<int> aLBARAN, Nullable<int> pETICION, Nullable<int> cOD_PALET_PADRE, Nullable<int> iNVOKER, string uSUARIO, string cULTURA, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var cOD_REFERENCIAParameter = cOD_REFERENCIA != null ?
                new ObjectParameter("COD_REFERENCIA", cOD_REFERENCIA) :
                new ObjectParameter("COD_REFERENCIA", typeof(string));
    
            var cOD_ESTADOParameter = cOD_ESTADO.HasValue ?
                new ObjectParameter("COD_ESTADO", cOD_ESTADO) :
                new ObjectParameter("COD_ESTADO", typeof(int));
    
            var cANTIDADParameter = cANTIDAD.HasValue ?
                new ObjectParameter("CANTIDAD", cANTIDAD) :
                new ObjectParameter("CANTIDAD", typeof(int));
    
            var aLBARANParameter = aLBARAN.HasValue ?
                new ObjectParameter("ALBARAN", aLBARAN) :
                new ObjectParameter("ALBARAN", typeof(int));
    
            var pETICIONParameter = pETICION.HasValue ?
                new ObjectParameter("PETICION", pETICION) :
                new ObjectParameter("PETICION", typeof(int));
    
            var cOD_PALET_PADREParameter = cOD_PALET_PADRE.HasValue ?
                new ObjectParameter("COD_PALET_PADRE", cOD_PALET_PADRE) :
                new ObjectParameter("COD_PALET_PADRE", typeof(int));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cULTURAParameter = cULTURA != null ?
                new ObjectParameter("CULTURA", cULTURA) :
                new ObjectParameter("CULTURA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_PALETS", cOD_REFERENCIAParameter, cOD_ESTADOParameter, cANTIDADParameter, aLBARANParameter, pETICIONParameter, cOD_PALET_PADREParameter, iNVOKERParameter, uSUARIOParameter, cULTURAParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_RECEPCIONES_CAB(Nullable<int> aLBARAN, Nullable<int> eSTADO, Nullable<int> iD_EMPRESA, Nullable<System.DateTime> fECH_CREACION, Nullable<System.DateTime> fECH_LLEGADA, Nullable<int> iNVOKER, string uSUARIO, string cULTURA, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var aLBARANParameter = aLBARAN.HasValue ?
                new ObjectParameter("ALBARAN", aLBARAN) :
                new ObjectParameter("ALBARAN", typeof(int));
    
            var eSTADOParameter = eSTADO.HasValue ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(int));
    
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(int));
    
            var fECH_CREACIONParameter = fECH_CREACION.HasValue ?
                new ObjectParameter("FECH_CREACION", fECH_CREACION) :
                new ObjectParameter("FECH_CREACION", typeof(System.DateTime));
    
            var fECH_LLEGADAParameter = fECH_LLEGADA.HasValue ?
                new ObjectParameter("FECH_LLEGADA", fECH_LLEGADA) :
                new ObjectParameter("FECH_LLEGADA", typeof(System.DateTime));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cULTURAParameter = cULTURA != null ?
                new ObjectParameter("CULTURA", cULTURA) :
                new ObjectParameter("CULTURA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_RECEPCIONES_CAB", aLBARANParameter, eSTADOParameter, iD_EMPRESAParameter, fECH_CREACIONParameter, fECH_LLEGADAParameter, iNVOKERParameter, uSUARIOParameter, cULTURAParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_RECEPCIONES_LIN(Nullable<int> aLBARAN, Nullable<int> cOD_LINEA, string cOD_REFERENCIA, Nullable<int> cANTIDAD, Nullable<int> cANTIDAD_MAL_ESTADO, Nullable<int> eXCEDENTE, Nullable<int> fALTA, Nullable<int> iNVOKER, string uSUARIO, string cULTURA, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var aLBARANParameter = aLBARAN.HasValue ?
                new ObjectParameter("ALBARAN", aLBARAN) :
                new ObjectParameter("ALBARAN", typeof(int));
    
            var cOD_LINEAParameter = cOD_LINEA.HasValue ?
                new ObjectParameter("COD_LINEA", cOD_LINEA) :
                new ObjectParameter("COD_LINEA", typeof(int));
    
            var cOD_REFERENCIAParameter = cOD_REFERENCIA != null ?
                new ObjectParameter("COD_REFERENCIA", cOD_REFERENCIA) :
                new ObjectParameter("COD_REFERENCIA", typeof(string));
    
            var cANTIDADParameter = cANTIDAD.HasValue ?
                new ObjectParameter("CANTIDAD", cANTIDAD) :
                new ObjectParameter("CANTIDAD", typeof(int));
    
            var cANTIDAD_MAL_ESTADOParameter = cANTIDAD_MAL_ESTADO.HasValue ?
                new ObjectParameter("CANTIDAD_MAL_ESTADO", cANTIDAD_MAL_ESTADO) :
                new ObjectParameter("CANTIDAD_MAL_ESTADO", typeof(int));
    
            var eXCEDENTEParameter = eXCEDENTE.HasValue ?
                new ObjectParameter("EXCEDENTE", eXCEDENTE) :
                new ObjectParameter("EXCEDENTE", typeof(int));
    
            var fALTAParameter = fALTA.HasValue ?
                new ObjectParameter("FALTA", fALTA) :
                new ObjectParameter("FALTA", typeof(int));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cULTURAParameter = cULTURA != null ?
                new ObjectParameter("CULTURA", cULTURA) :
                new ObjectParameter("CULTURA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_RECEPCIONES_LIN", aLBARANParameter, cOD_LINEAParameter, cOD_REFERENCIAParameter, cANTIDADParameter, cANTIDAD_MAL_ESTADOParameter, eXCEDENTEParameter, fALTAParameter, iNVOKERParameter, uSUARIOParameter, cULTURAParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_REFERENCIAS(string cOD_REFERENCIA, Nullable<int> iD_EMPRESA, string dES_REFERENCIA, Nullable<double> pRECIO, string iMAGEN, Nullable<bool> eSTADO, Nullable<int> iNVOKER, string uSUARIO, string cULTURA, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var cOD_REFERENCIAParameter = cOD_REFERENCIA != null ?
                new ObjectParameter("COD_REFERENCIA", cOD_REFERENCIA) :
                new ObjectParameter("COD_REFERENCIA", typeof(string));
    
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(int));
    
            var dES_REFERENCIAParameter = dES_REFERENCIA != null ?
                new ObjectParameter("DES_REFERENCIA", dES_REFERENCIA) :
                new ObjectParameter("DES_REFERENCIA", typeof(string));
    
            var pRECIOParameter = pRECIO.HasValue ?
                new ObjectParameter("PRECIO", pRECIO) :
                new ObjectParameter("PRECIO", typeof(double));
    
            var iMAGENParameter = iMAGEN != null ?
                new ObjectParameter("IMAGEN", iMAGEN) :
                new ObjectParameter("IMAGEN", typeof(string));
    
            var eSTADOParameter = eSTADO.HasValue ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(bool));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cULTURAParameter = cULTURA != null ?
                new ObjectParameter("CULTURA", cULTURA) :
                new ObjectParameter("CULTURA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_REFERENCIAS", cOD_REFERENCIAParameter, iD_EMPRESAParameter, dES_REFERENCIAParameter, pRECIOParameter, iMAGENParameter, eSTADOParameter, iNVOKERParameter, uSUARIOParameter, cULTURAParameter, rETCODE, mENSAJE);
        }
    }
}
