//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOS_PICKING
    {
        public int COD_MOVIMIENTO { get; set; }
        public Nullable<int> COD_PETICION { get; set; }
        public Nullable<int> COD_PALET { get; set; }
        public Nullable<System.DateTime> FECH_REALIZACION { get; set; }
        public Nullable<bool> REALIZADO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    
        public virtual ORDEN_SALIDA_CAB ORDEN_SALIDA_CAB { get; set; }
        public virtual PALETS PALETS { get; set; }
    }
}
