//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_SALIDA_INCIDENCIAS
    {
        public int ID_INCIDENCIA { get; set; }
        public Nullable<int> COD_PETICION { get; set; }
        public string DES_INCIDENCIA { get; set; }
        public Nullable<bool> RESUELTA { get; set; }
    
        public virtual ORDEN_SALIDA_CAB ORDEN_SALIDA_CAB { get; set; }
    }
}
