//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_SALIDA_CAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_SALIDA_CAB()
        {
            this.ORDEN_SALIDA_LIN = new HashSet<ORDEN_SALIDA_LIN>();
            this.MOVIMIENTOS_PICKING = new HashSet<MOVIMIENTOS_PICKING>();
        }
    
        public int COD_PETICION { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string DIRECCION_ENTREGA { get; set; }
        public string COD_POSTAL { get; set; }
        public string POBLACION { get; set; }
        public string PROVINCIA { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
    
        public virtual ESTADOS_ORDEN_SALIDA ESTADOS_ORDEN_SALIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_SALIDA_LIN> ORDEN_SALIDA_LIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTOS_PICKING> MOVIMIENTOS_PICKING { get; set; }
    }
}
