//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALETS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PALETS()
        {
            this.INCIDENCIAS_PALETS = new HashSet<INCIDENCIAS_PALETS>();
            this.MOVIMIENTOS_PICKING = new HashSet<MOVIMIENTOS_PICKING>();
        }
    
        public int COD_PALET { get; set; }
        public string COD_REFERENCIA { get; set; }
        public string UBICACION { get; set; }
        public Nullable<int> COD_ESTADO { get; set; }
        public Nullable<System.DateTime> FECH_INSERT { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<int> ALBARAN_RECEPCION { get; set; }
        public string ETIQUETA { get; set; }
    
        public virtual ESTADOS_PALETS ESTADOS_PALETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INCIDENCIAS_PALETS> INCIDENCIAS_PALETS { get; set; }
        public virtual REFERENCIAS REFERENCIAS { get; set; }
        public virtual UBICACIONES UBICACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTOS_PICKING> MOVIMIENTOS_PICKING { get; set; }
    }
}
