//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCIONES_LIN
    {
        public int ALBARAN { get; set; }
        public int COD_LINEA { get; set; }
        public string COD_REFERENCIA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    
        public virtual RECEPCIONES_CAB RECEPCIONES_CAB { get; set; }
        public virtual REFERENCIAS REFERENCIAS { get; set; }
    }
}
