//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCIONES_CAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECEPCIONES_CAB()
        {
            this.RECEPCIONES_LIN = new HashSet<RECEPCIONES_LIN>();
        }
    
        public int ALBARAN { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string PROVEEDOR { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<System.DateTime> FECH_LLEGADA { get; set; }
    
        public virtual ESTADOS_RECEPCION ESTADOS_RECEPCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEPCIONES_LIN> RECEPCIONES_LIN { get; set; }
    }
}
