//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERENCIAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REFERENCIAS()
        {
            this.ORDEN_SALIDA_LIN = new HashSet<ORDEN_SALIDA_LIN>();
            this.PALETS = new HashSet<PALETS>();
            this.RECEPCIONES_LIN = new HashSet<RECEPCIONES_LIN>();
        }
    
        public string COD_REFERENCIA { get; set; }
        public Nullable<int> ID_EMPRESA { get; set; }
        public string DES_REFERENCIA { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public string IMAGEN { get; set; }
        public Nullable<bool> ESTADO { get; set; }
    
        public virtual EMPRESAS EMPRESAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_SALIDA_LIN> ORDEN_SALIDA_LIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PALETS> PALETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEPCIONES_LIN> RECEPCIONES_LIN { get; set; }
    }
}
