//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MOVIMIENTOS_PICKING
    {
        public int COD_MOVIMIENTO { get; set; }
        public Nullable<int> COD_PETICION { get; set; }
        public Nullable<int> COD_PALET { get; set; }
        public string COD_REFERENCIA { get; set; }
        public string DES_REFERENCIA { get; set; }
        public string UBICACION { get; set; }
    }
}
