//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ORDEN_SALIDA_LIN
    {
        public int COD_PETICION { get; set; }
        public int COD_LINEA { get; set; }
        public string COD_REFERENCIA { get; set; }
        public string DES_REFERENCIA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<int> STOCK { get; set; }
    }
}
