//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ORDEN_SALIDA_LIN
    {
        public int COD_PETICION { get; set; }
        public int COD_LINEA { get; set; }
        public string COD_REFERENCIA { get; set; }
        public string DES_REFERENCIA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<int> STOCK { get; set; }
    }
}
