//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PALETS
    {
        public int COD_PALET { get; set; }
        public string DESC_ESTADO { get; set; }
        public Nullable<int> COD_ESTADO { get; set; }
        public string COD_REFERENCIA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string UBICACION { get; set; }
        public string DESC_UBICACION { get; set; }
        public string CALLE { get; set; }
        public string POSICION { get; set; }
        public Nullable<System.DateTime> FECH_INSERT { get; set; }
        public int ALBARAN_RECEPCION { get; set; }
        public int PETICION_SALIDA { get; set; }
        public int PALET_PADRE { get; set; }
    }
}
