//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PALETS
    {
        public int COD_PALET { get; set; }
        public Nullable<int> COD_ESTADO { get; set; }
        public string DESC_ESTADO { get; set; }
        public string COD_REFERENCIA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string UBICACION { get; set; }
        public string DESC_UBICACION { get; set; }
        public string CALLE { get; set; }
        public string POSICION { get; set; }
        public Nullable<System.DateTime> FECH_INSERT { get; set; }
        public Nullable<int> ALBARAN_RECEPCION { get; set; }
        public Nullable<int> PETICION_SALIDA { get; set; }
        public Nullable<int> PALET_PADRE { get; set; }
    }
}
