//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_REFERENCIAS
    {
        public string COD_REFERENCIA { get; set; }
        public Nullable<int> ID_EMPRESA { get; set; }
        public string DES_REFERENCIA { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public string IMAGEN { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<int> STOCK { get; set; }
    }
}
