//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RECEPCIONES_CAB
    {
        public int ALBARAN { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string DES_ESTADO { get; set; }
        public string PROVEEDOR { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<System.DateTime> FECH_LLEGADA { get; set; }
        public Nullable<int> CANTIDAD_LINEAS { get; set; }
    }
}
