//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SQL
    {
        public int ID { get; set; }
        public string TABLA { get; set; }
        public string CAMPO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> POSICION { get; set; }
        public string TIPO { get; set; }
        public int DIMENSION { get; set; }
        public int PERMITE_NULOS { get; set; }
        public string DEFECTO { get; set; }
        public string CLAVE { get; set; }
        public int INDICES { get; set; }
        public string COLLATE { get; set; }
        public string GRUPO_FICHEROS { get; set; }
        public Nullable<int> KBYTES { get; set; }
        public Nullable<int> MBYTES { get; set; }
        public Nullable<int> GROWTH { get; set; }
        public Nullable<int> N_FILES { get; set; }
        public string GRUPO { get; set; }
        public string TRIGGERS { get; set; }
        public string name { get; set; }
        public Nullable<int> object_id { get; set; }
        public Nullable<int> data_space_id { get; set; }
    }
}
