//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SQL_FICHEROS
    {
        public string BBDD { get; set; }
        public string FICHERO { get; set; }
        public string RUTA_FICHERO { get; set; }
        public string GRUPO_FICHERO { get; set; }
        public Nullable<int> TOTAL_MB { get; set; }
        public Nullable<int> LIBRE_MB { get; set; }
        public Nullable<int> PORCENTAJE_LIBRE { get; set; }
    }
}
