 
 INSERT INTO UBICACIONES VALUES('U001','ZONA AZUL','A',1)
 INSERT INTO UBICACIONES VALUES('U002','ZONA AZUL','A',2)

  INSERT INTO UBICACIONES VALUES('U003','ZONA AZUL','B',1)
  INSERT INTO UBICACIONES VALUES('U004','ZONA AZUL','B',2)
 
 INSERT INTO UBICACIONES VALUES('U005','ZONA DIPOSITIVOS NO DISPONIBLES','A',1);
  INSERT INTO UBICACIONES VALUES('U006','ZONA DIPOSITIVOS NO DISPONIBLES','A',2);

   INSERT INTO UBICACIONES VALUES('U007','ENVIADO','A',1);

 
