 INSERT INTO RECEPCIONES_CAB VALUES('ALB001','SAMSUNG',GETDATE()-1,1,GETDATE());

 INSERT INTO RECEPCIONES_LIN VALUES('ALB001',1,'A01',100);

 
 
 INSERT INTO PALETS(REFERENCIA,CANTIDAD,ALBARAN_RECEPCION,UBICACION,ESTADO,F_INSERT) VALUES('A01',60,'ALB001','U001',1,GETDATE());
 INSERT INTO PALETS(REFERENCIA,CANTIDAD,ALBARAN_RECEPCION,UBICACION,ESTADO,F_INSERT) VALUES('A01',40,'ALB001','U005',2,GETDATE());