

SELECT 
	PL.PALET,
	PL.REFERENCIA,
	PL.UBICACION,
	PL.F_INSERT,
	PL.CANTIDAD-ISNULL(O1.CANTIDAD,0) AS STOCK
FROM 
	PALETS PL
OUTER APPLY(
SELECT SUM(ISNULL(PM.CANTIDAD,0)) AS CANTIDAD 
FROM 
	PICKING_MOV PM
WHERE 
	PL.PALET = PM.PALET AND (PM.ESTADO_PICKING = 0 OR PM.ESTADO_PICKING IS NULL)) O1
WHERE PL.ESTADO = 2 AND  PL.REFERENCIA = 'A01' ORDER BY F_INSERT ASC;







SELECT * FROM PICKING_MOV
SELECT * FROM PALETS;


INSERT INTO PICKING_MOV(PEDIDO,LINEA,REFERENCIA,CANTIDAD,PALET,UBICACION,ESTADO_PICKING) VALUES('P14',1,'A01',3,1001,'U005',0)

UPDATE PICKING_MOV SET ESTADO_PICKING = 0 WHERE PEDIDO = 'P1';

DELETE PICKING_MOV;

UPDATE ORDEN_SALIDA_CAB SET ID_ESTADO = 2 WHERE PETICION =  'P2'

EXEC PA_PICKING_MOV 'P1',0,0,'';

select * from UBICACIONES;

SELECT * FROM PICKING_MOV;

SELECT * FROM ESTADOS_PALETS;
 
SELECT * FROM ESTADOS_PEDIDOS;

SELECT * FROM AUX_RECEPCIONES_LIN
 
 DBCC CHECKIDENT ('ESTADOS_PEDIDOS', RESEED,0) 
 DBCC CHECKIDENT ('ESTADOS_PEDIDOS', RESEED, 1)
INSERT INTO ESTADOS_PEDIDOS(DESC_ESTADO) VALUES('PICKING')









 