CREATE TABLE PICKING_MOV
(
	PEDIDO VARCHAR(12) NOT NULL,
	REFERENCIA VARCHAR(20) NOT NULL,
	LINEA INT NOT NULL, 
	PALET INT NOT NULL,
	CANTIDAD INT,
	UBICACION VARCHAR(30) NOT NULL,
	ESTADO_PICKING INT,
		
	PRIMARY KEY(PEDIDO,REFERENCIA,LINEA,PALET,UBICACION),
	CONSTRAINT FK_PEDIDO_PICKING FOREIGN KEY (PEDIDO,LINEA) REFERENCES ORDEN_SALIDA_LIN(PETICION,LINEA),
	CONSTRAINT FK_PALET_PICKING FOREIGN KEY (PALET) REFERENCES PALETS(PALET),
	CONSTRAINT FK_REFERENCIA_PICKING FOREIGN KEY (REFERENCIA) REFERENCES REFERENCIAS(REFERENCIA) 
)