


BEGIN TRANSACTION

BEGIN TRY
	CREATE TABLE ESTADOS_PEDIDOS
	( 

		ID_ESTADO INT PRIMARY KEY IDENTITY(1,1),
		DESC_ESTADO VARCHAR(100)
	)

	
	INSERT INTO ESTADOS_PEDIDOS VALUES('PENDIENTE');
	INSERT INTO ESTADOS_PEDIDOS VALUES('TRASPASADO ICP');
	INSERT INTO ESTADOS_PEDIDOS VALUES('CANCELADO');
	INSERT INTO ESTADOS_PEDIDOS VALUES('RECEPCIONADO');
	INSERT INTO ESTADOS_PEDIDOS VALUES('ENVIADO');
	

	COMMIT;
END TRY
BEGIN CATCH
	ROLLBACK
	PRINT('ERROR');
END CATCH
GO