CREATE TABLE [ORDEN_SALIDA_CAB] (
	PETICION varchar(12) NOT NULL,
	NOMBRE_CLIENTE varchar(50) NOT NULL,
	DIRECCION_ENTREGA varchar(300) NOT NULL,
	CODIGO_POSTAL varchar(10) NOT NULL,
	POBLACION varchar(50) NOT NULL,
	PROVINCIA varchar(50) NOT NULL,
	TELEFONO varchar(20) NOT NULL,
	F_CREACION datetime NOT NULL,
  CONSTRAINT [PK_ORDEN_SALIDA_CAB] PRIMARY KEY CLUSTERED
  (
  [PETICION] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [ORDEN_SALIDA_LIN] (
	PETICION varchar(12) NOT NULL,
	LINEA integer NOT NULL,
	REFERENCIA varchar(20) NOT NULL,
	CANTIDAD integer NOT NULL,
  CONSTRAINT [PK_ORDEN_SALIDA_LIN] PRIMARY KEY CLUSTERED
  (
  [PETICION] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [PALETS] (
	PALET integer NOT NULL,
	REFERENCIA varchar(20) NOT NULL,
	CANTIDAD integer NOT NULL,
	ALBARAN_RECEPCION varchar(20) NOT NULL,
	UBICACION varchar(30) NOT NULL,
	ESTADO integer NOT NULL,
	F_INSERT datetime NOT NULL,
  CONSTRAINT [PK_PALETS] PRIMARY KEY CLUSTERED
  (
  [PALET] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [RECEPCIONES_CAB] (
	ALBARAN varchar(12) NOT NULL,
	PROVEEDOR varchar(20) NOT NULL,
	F_CREACION datetime NOT NULL,
	ESTADO integer NOT NULL,
	F_CONFIRMACION datetime NOT NULL,
  CONSTRAINT [PK_RECEPCIONES_CAB] PRIMARY KEY CLUSTERED
  (
  [ALBARAN] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [RECEPCIONES_LIN] (
	ALBARAN varchar(12) NOT NULL,
	LINEA integer NOT NULL,
	REFERENCIA varchar(20) NOT NULL,
	CANTIDAD integer NOT NULL,
  CONSTRAINT [PK_RECEPCIONES_LIN] PRIMARY KEY CLUSTERED
  (
  [ALBARAN] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [REFERENCIAS] (
	REFERENCIA varchar(20) NOT NULL,
	DES_REFERENCIA varchar(500) NOT NULL,
	PRECIO float NOT NULL,
	F_CREACION datetime NOT NULL,
	IMAGEN varchar(2000) NOT NULL,
  CONSTRAINT [PK_REFERENCIAS] PRIMARY KEY CLUSTERED
  (
  [REFERENCIA] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [UBICACIONES] (
	UBICACION varchar(30) NOT NULL,
	DES_UBICACION varchar(200) NOT NULL,
	CALLE varchar(3) NOT NULL,
	POSICION integer NOT NULL,
  CONSTRAINT [PK_UBICACIONES] PRIMARY KEY CLUSTERED
  (
  [UBICACION] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO

ALTER TABLE [ORDEN_SALIDA_LIN] WITH CHECK ADD CONSTRAINT [ORDEN_SALIDA_LIN_fk0] FOREIGN KEY ([PETICION]) REFERENCES [ORDEN_SALIDA_CAB]([PETICION])
ON UPDATE CASCADE
GO
ALTER TABLE [ORDEN_SALIDA_LIN] CHECK CONSTRAINT [ORDEN_SALIDA_LIN_fk0]
GO
ALTER TABLE [ORDEN_SALIDA_LIN] WITH CHECK ADD CONSTRAINT [ORDEN_SALIDA_LIN_fk1] FOREIGN KEY ([REFERENCIA]) REFERENCES [REFERENCIAS]([REFERENCIA])
ON UPDATE CASCADE
GO
ALTER TABLE [ORDEN_SALIDA_LIN] CHECK CONSTRAINT [ORDEN_SALIDA_LIN_fk1]
GO

ALTER TABLE [PALETS] WITH CHECK ADD CONSTRAINT [PALETS_fk0] FOREIGN KEY ([REFERENCIA]) REFERENCES [REFERENCIAS]([REFERENCIA])
ON UPDATE CASCADE
GO
ALTER TABLE [PALETS] CHECK CONSTRAINT [PALETS_fk0]
GO
ALTER TABLE [PALETS] WITH CHECK ADD CONSTRAINT [PALETS_fk1] FOREIGN KEY ([UBICACION]) REFERENCES [UBICACIONES]([UBICACION])
ON UPDATE CASCADE
GO
ALTER TABLE [PALETS] CHECK CONSTRAINT [PALETS_fk1]
GO


ALTER TABLE [RECEPCIONES_LIN] WITH CHECK ADD CONSTRAINT [RECEPCIONES_LIN_fk0] FOREIGN KEY ([ALBARAN]) REFERENCES [RECEPCIONES_CAB]([ALBARAN])
ON UPDATE CASCADE
GO
ALTER TABLE [RECEPCIONES_LIN] CHECK CONSTRAINT [RECEPCIONES_LIN_fk0]
GO
ALTER TABLE [RECEPCIONES_LIN] WITH CHECK ADD CONSTRAINT [RECEPCIONES_LIN_fk1] FOREIGN KEY ([REFERENCIA]) REFERENCES [REFERENCIAS]([REFERENCIA])
ON UPDATE CASCADE
GO
ALTER TABLE [RECEPCIONES_LIN] CHECK CONSTRAINT [RECEPCIONES_LIN_fk1]
GO



