ALTER FUNCTION dbo.CONSULTAR_STOCK_REFERENCIA
(@COD_REFERENCIA AS VARCHAR(30))

RETURNS INT

AS 

BEGIN

	DECLARE  @CANTIDAD_TOTAL INT,
		 @CANTIDAD_BLOQUEADA INT,
		 @STOCK INT


	SELECT @CANTIDAD_TOTAL = SUM(CANTIDAD) 
	FROM PALETS 
	WHERE PALETS.COD_REFERENCIA = @COD_REFERENCIA
	AND (COD_ESTADO = 1 OR COD_ESTADO = 2)

	SELECT @CANTIDAD_BLOQUEADA = SUM(MOVIMIENTOS_PICKING.CANTIDAD)
	FROM MOVIMIENTOS_PICKING	
	JOIN PALETS
	ON MOVIMIENTOS_PICKING.COD_PALET = PALETS.COD_PALET
	AND COD_REFERENCIA = @COD_REFERENCIA
	WHERE REALIZADO = 0

	SET @STOCK = ISNULL(@CANTIDAD_TOTAL,0)-ISNULL(@CANTIDAD_BLOQUEADA,0)

   RETURN @STOCK

END;