ALTER FUNCTION dbo.COMPROBAR_DISPONIBILIDAD_PEDIDO
(@PETICION AS INT)

RETURNS BIT

AS 

BEGIN

--Consulta las lineas de una peticion y si hay alguna linea en la que no hay stock, devuelve false

	DECLARE  @REFERENCIA VARCHAR(30),
		 @FILAS_DEVUELTAS INT = 0,
		 @SALIDA BIT = 0

	SELECT  @FILAS_DEVUELTAS += 1
	FROM ORDEN_SALIDA_LIN
	JOIN ORDEN_SALIDA_CAB
	ON ORDEN_SALIDA_CAB.COD_PETICION = ORDEN_SALIDA_LIN.COD_PETICION
	WHERE ORDEN_SALIDA_LIN.COD_PETICION = @PETICION
	AND CANTIDAD > dbo.CONSULTAR_STOCK_REFERENCIA(COD_REFERENCIA)
	AND ESTADO = 1

	IF @FILAS_DEVUELTAS = 0
	BEGIN
		SET @SALIDA = 1
	END

	RETURN @SALIDA	
END;



