
-- ==================================================================================== 
-- 					CREAR TABLAS
-- ====================================================================================


CREATE TABLE EMPRESAS (
	ID_EMPRESA INT NOT NULL,
	DES_EMPRESA VARCHAR(50),
	NOM_USUARIO VARCHAR(30),
	PASSWORD VARCHAR(30),
	LOGO VARCHAR (500),
	PRIMARY KEY (ID_EMPRESA)
);



CREATE TABLE REFERENCIAS (
	COD_REFERENCIA varchar(30) NOT NULL,
	ID_EMPRESA INT,
	DES_REFERENCIA varchar(500),
	PRECIO FLOAT,
	FECH_CREACION DATE,
	IMAGEN varchar(2000),
	BLOQUEADA BIT,
	PRIMARY KEY (COD_REFERENCIA)
);

CREATE TABLE RECEPCIONES_LIN (
	ALBARAN INT,
	COD_LINEA INT,
	COD_REFERENCIA varchar(30),
	CANTIDAD INT,
	PRIMARY KEY (ALBARAN,COD_LINEA)
);

CREATE TABLE RECEPCIONES_CAB (
	ALBARAN INT NOT NULL,
	ESTADO INT,
	ID_EMPRESA INT,
	FECH_CREACION DATE,
	FECH_LLEGADA DATE,
	PRIMARY KEY (ALBARAN)
);

CREATE TABLE ESTADOS_RECEPCION (
	COD_ESTADO INT NOT NULL ,
	DES_ESTADO varchar(50),
	PRIMARY KEY (COD_ESTADO)
);


CREATE TABLE PALETS (
	COD_PALET INT NOT NULL ,
	COD_REFERENCIA varchar(30),
	UBICACION varchar(30),
	COD_ESTADO INT,
	FECH_INSERT DATE,
	CANTIDAD INT,
	ALBARAN_RECEPCION INT,
	PETICION_SALIDA INT,
	PALET_PADRE INT,
	ETIQUETA VARCHAR(4000),
	PRIMARY KEY (COD_PALET)
);

CREATE TABLE UBICACIONES (
	COD_UBICACION varchar(30) NOT NULL,
	DESC_UBICACION varchar(200),
	CALLE varchar(60),
	POSICION varchar(30),
	LLENA INT,
	PRIMARY KEY (COD_UBICACION)
);

CREATE TABLE ESTADOS_PALETS (
	COD_ESTADO INT NOT NULL,
	DESC_ESTADO varchar(200),
	PRIMARY KEY (COD_ESTADO)
);


CREATE TABLE ORDEN_SALIDA_LIN (
	COD_PETICION INT NOT NULL,
	COD_LINEA INT,
	COD_REFERENCIA varchar(30),
	CANTIDAD INT,
	PRIMARY KEY (COD_PETICION,COD_LINEA)
);

CREATE TABLE ORDEN_SALIDA_CAB (
	COD_PETICION INT NOT NULL ,
	ESTADO INT,
	ID_EMPRESA INT,
	DIRECCION_ENTREGA varchar(300),
	COD_POSTAL varchar(10),
	POBLACION varchar(100),
	PROVINCIA varchar(100),
	TELEFONO varchar(20),
	FECH_CREACION DATE,
	PRIMARY KEY (COD_PETICION)
);

CREATE TABLE ESTADOS_ORDEN_SALIDA (
	COD_ESTADO INT NOT NULL,
	DES_ESTADO varchar(200),
	PRIMARY KEY (COD_ESTADO)
);

CREATE TABLE MOVIMIENTOS_PICKING (
	COD_MOVIMIENTO INT NOT NULL IDENTITY(1,1),	
	COD_PETICION INT,
	COD_PALET INT,
	FECH_REALIZACION DATE,
	REALIZADO BIT,
	CANTIDAD INT,
	PRIMARY KEY (COD_MOVIMIENTO)
);

CREATE TABLE MOVIMIENTOS_PICKING_LOG (
	COD_MOVIMIENTO_LOG INT NOT NULL IDENTITY(1,1),	
	COD_PETICION INT,
	COD_PALET INT,
	FECH_REALIZACION DATE,
	CANTIDAD INT,
	UBICACION VARCHAR(30),
	PRIMARY KEY (COD_MOVIMIENTO_LOG)
);

CREATE TABLE ORDEN_SALIDA_INCIDENCIAS (
	ID_INCIDENCIA INT NOT NULL IDENTITY(1,1),
	COD_PETICION INT,
	DES_INCIDENCIA varchar(500),
	RESUELTA BIT,
	PRIMARY KEY (ID_INCIDENCIA)
);

ALTER TABLE ORDEN_SALIDA_INCIDENCIAS ADD CONSTRAINT ORDEN_SALIDA_INCIDENCIAS_fk0 FOREIGN KEY (COD_PETICION) REFERENCES ORDEN_SALIDA_CAB(COD_PETICION);

ALTER TABLE MOVIMIENTOS_PICKING_LOG ADD CONSTRAINT MOVIMIENTOS_PICKING_LOG_fk0 FOREIGN KEY (COD_PETICION) REFERENCES ORDEN_SALIDA_CAB(COD_PETICION);

ALTER TABLE MOVIMIENTOS_PICKING_LOG ADD CONSTRAINT MOVIMIENTOS_PICKING_LOG_fk1 FOREIGN KEY (COD_PALET) REFERENCES PALETS(COD_PALET);

ALTER TABLE MOVIMIENTOS_PICKING_LOG ADD CONSTRAINT MOVIMIENTOS_PICKING_LOG_fk2 FOREIGN KEY (UBICACION) REFERENCES UBICACIONES(COD_UBICACION);

ALTER TABLE MOVIMIENTOS_PICKING ADD CONSTRAINT MOVIMIENTOS_PICKING_fk0 FOREIGN KEY (COD_PETICION) REFERENCES ORDEN_SALIDA_CAB(COD_PETICION);

ALTER TABLE MOVIMIENTOS_PICKING ADD CONSTRAINT MOVIMIENTOS_PICKING_fk1 FOREIGN KEY (COD_PALET) REFERENCES PALETS(COD_PALET);

ALTER TABLE REFERENCIAS ADD CONSTRAINT REFERENCIAS_fk0 FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA);

ALTER TABLE RECEPCIONES_LIN ADD CONSTRAINT RECEPCIONES_LIN_fk0 FOREIGN KEY (ALBARAN) REFERENCES RECEPCIONES_CAB(ALBARAN);

ALTER TABLE RECEPCIONES_LIN ADD CONSTRAINT RECEPCIONES_LIN_fk1 FOREIGN KEY (COD_REFERENCIA) REFERENCES REFERENCIAS(COD_REFERENCIA);

ALTER TABLE RECEPCIONES_CAB ADD CONSTRAINT RECEPCIONES_CAB_fk0 FOREIGN KEY (ESTADO) REFERENCES ESTADOS_RECEPCION(COD_ESTADO);

ALTER TABLE RECEPCIONES_CAB ADD CONSTRAINT RECEPCIONES_CAB_fk1 FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA);

ALTER TABLE PALETS ADD CONSTRAINT PALETS_fk0 FOREIGN KEY (COD_REFERENCIA) REFERENCES REFERENCIAS(COD_REFERENCIA);

ALTER TABLE PALETS ADD CONSTRAINT PALETS_fk1 FOREIGN KEY (UBICACION) REFERENCES UBICACIONES(COD_UBICACION);

ALTER TABLE PALETS ADD CONSTRAINT PALETS_fk2 FOREIGN KEY (COD_ESTADO) REFERENCES ESTADOS_PALETS(COD_ESTADO);

ALTER TABLE PALETS ADD CONSTRAINT PALETS_fk3 FOREIGN KEY (PALET_PADRE) REFERENCES PALETS(COD_PALET);


ALTER TABLE ORDEN_SALIDA_LIN ADD CONSTRAINT ORDEN_SALIDA_LIN_fk0 FOREIGN KEY (COD_PETICION) REFERENCES ORDEN_SALIDA_CAB(COD_PETICION);

ALTER TABLE ORDEN_SALIDA_LIN ADD CONSTRAINT ORDEN_SALIDA_LIN_fk1 FOREIGN KEY (COD_REFERENCIA) REFERENCES REFERENCIAS(COD_REFERENCIA);

ALTER TABLE ORDEN_SALIDA_CAB ADD CONSTRAINT ORDEN_SALIDA_CAB_fk0 FOREIGN KEY (ESTADO) REFERENCES ESTADOS_ORDEN_SALIDA(COD_ESTADO);

ALTER TABLE ORDEN_SALIDA_CAB ADD CONSTRAINT ORDEN_SALIDA_CAB_fk1 FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA);


-- =============================================================================
-- 				INSERTAR DATOS 
-- =============================================================================

-- INSERTAR EN TABLA EMPRESAS

INSERT INTO EMPRESAS VALUES (2,'WORTEN', 'worten', '123');

INSERT INTO EMPRESAS VALUES (3,'XIAOMI', 'xiaomi', '123');

-- INSERTAR REFERENCIAS

INSERT INTO REFERENCIAS VALUES('XI_00001',3,'XIAOMI Mi11 Pro',459.99,SYSDATETIME(),'/Img/Xiaomi/Mi11_Pro.jpg');

INSERT INTO REFERENCIAS VALUES('XI_00002',3,'XIAOMI RedmiNote 9',219.99,SYSDATETIME(),'/Img/Xiaomi/RedmiNote_9.jpg');

INSERT INTO REFERENCIAS VALUES('XI_00003',3,'XIAOMI Mi10 Lite',259.99,SYSDATETIME(),'/Img/Xiaomi/Mi10_Lite.jpg');

INSERT INTO REFERENCIAS VALUES('WO_00001',2,'UltraFresh LG 1.2',699.99,SYSDATETIME(),'/Img/Worten/UltraFresh_LG_1.2.jpg');

INSERT INTO REFERENCIAS VALUES('WO_00002',2,'HP Pavillion 3K',1499.99,SYSDATETIME(),'/Img/Worten/HP_Pavillion_3K.jpg');

INSERT INTO REFERENCIAS VALUES('WO_00003',2,'LG Curved OLED 4.0 TV 4K',2499.99,SYSDATETIME(),'/Img/Worten/LG_Curved_OLED_4.0_TV_4K.jpg');

-- INSERTAR ESTADOS_RECEPCION

INSERT INTO ESTADOS_RECEPCION VALUES (1,'PENDIENTE');

INSERT INTO ESTADOS_RECEPCION VALUES (2,'CERRADO');

INSERT INTO ESTADOS_RECEPCION VALUES (3,'CANCELADO');

-- INSERTAR ESTADOS_PALETS

INSERT INTO ESTADOS_PALETS VALUES (1,'LIBRE');

INSERT INTO ESTADOS_PALETS VALUES (2,'BLOQUEADO');

INSERT INTO ESTADOS_PALETS VALUES (3,'DAÑADO');

INSERT INTO ESTADOS_PALETS VALUES (4,'EJECUTADO');

INSERT INTO ESTADOS_PALETS VALUES (5,'ENVIADO');

INSERT INTO ESTADOS_PALETS VALUES (6,'INCIDENCIA');

INSERT INTO ESTADOS_PALETS VALUES (7,'ELIMINADO');

-- INSERTAR ESTADOS_ORDEN_SALIDA

INSERT INTO ESTADOS_ORDEN_SALIDA VALUES (1,'CREADO');

INSERT INTO ESTADOS_ORDEN_SALIDA VALUES (2,'ASIGNADO');

INSERT INTO ESTADOS_ORDEN_SALIDA VALUES (3,'EJECUTADO');

INSERT INTO ESTADOS_ORDEN_SALIDA VALUES (4,'REVISADO');

INSERT INTO ESTADOS_ORDEN_SALIDA VALUES (5,'CERRADO');

INSERT INTO ESTADOS_ORDEN_SALIDA VALUES (6,'CANCELADO');

INSERT INTO ESTADOS_ORDEN_SALIDA VALUES (7,'INCIDENCIA');

-- INSERTAR UBICACIONES

INSERT INTO UBICACIONES VALUES ('ZD_01_01','Zona de descarga','01','01',0);

INSERT INTO UBICACIONES VALUES ('ZR_01_01','Zona de revisión','01','01',0);

INSERT INTO UBICACIONES VALUES ('ZC_01_01','Zona de carga','01','01',0);

-- 0 ==> Vacio           1 ==> Lleno 
       
-- CALLE 1 

INSERT INTO UBICACIONES VALUES ('CA_01_01','Calle 01 Seccion 01','01','01',0);

INSERT INTO UBICACIONES VALUES ('CA_01_02','Calle 01 Seccion 02','01','02',0);

INSERT INTO UBICACIONES VALUES ('CA_01_03','Calle 01 Seccion 03','01','03',0);

INSERT INTO UBICACIONES VALUES ('CA_01_04','Calle 01 Seccion 04','01','04',0);

INSERT INTO UBICACIONES VALUES ('CA_01_05','Calle 01 Seccion 05','01','05',0);

INSERT INTO UBICACIONES VALUES ('CA_01_06','Calle 01 Seccion 06','01','06',0);

INSERT INTO UBICACIONES VALUES ('CA_01_07','Calle 01 Seccion 07','01','07',0);

INSERT INTO UBICACIONES VALUES ('CA_01_08','Calle 01 Seccion 08','01','08',0);

INSERT INTO UBICACIONES VALUES ('CA_01_09','Calle 01 Seccion 09','01','09',0);

INSERT INTO UBICACIONES VALUES ('CA_01_10','Calle 01 Seccion 10','01','10',0);

INSERT INTO UBICACIONES VALUES ('CA_01_11','Calle 01 Seccion 11','01','11',0);

INSERT INTO UBICACIONES VALUES ('CA_01_12','Calle 01 Seccion 12','01','12',0);

INSERT INTO UBICACIONES VALUES ('CA_01_13','Calle 01 Seccion 13','01','13',0);


 -- CALLE 2

INSERT INTO UBICACIONES VALUES ('CA_02_01','Calle 02 Seccion 01','02','01',0);

INSERT INTO UBICACIONES VALUES ('CA_02_02','Calle 02 Seccion 02','02','02',0);

INSERT INTO UBICACIONES VALUES ('CA_02_03','Calle 02 Seccion 03','02','03',0);

INSERT INTO UBICACIONES VALUES ('CA_02_04','Calle 02 Seccion 04','02','04',0);

INSERT INTO UBICACIONES VALUES ('CA_02_05','Calle 02 Seccion 05','02','05',0);

INSERT INTO UBICACIONES VALUES ('CA_02_06','Calle 02 Seccion 06','02','06',0);

INSERT INTO UBICACIONES VALUES ('CA_02_07','Calle 02 Seccion 07','02','07',0);

INSERT INTO UBICACIONES VALUES ('CA_02_08','Calle 02 Seccion 08','02','08',0);

INSERT INTO UBICACIONES VALUES ('CA_02_09','Calle 02 Seccion 09','02','09',0);

INSERT INTO UBICACIONES VALUES ('CA_02_10','Calle 02 Seccion 10','02','10',0);

INSERT INTO UBICACIONES VALUES ('CA_02_11','Calle 02 Seccion 11','02','11',0);

INSERT INTO UBICACIONES VALUES ('CA_02_12','Calle 02 Seccion 12','02','12',0);

INSERT INTO UBICACIONES VALUES ('CA_02_13','Calle 02 Seccion 13','02','13',0);

-- CALLE 3

INSERT INTO UBICACIONES VALUES ('CA_03_01','Calle 03 Seccion 01','03','01',0);

INSERT INTO UBICACIONES VALUES ('CA_03_02','Calle 03 Seccion 02','03','02',0);

INSERT INTO UBICACIONES VALUES ('CA_03_03','Calle 03 Seccion 03','03','03',0);

INSERT INTO UBICACIONES VALUES ('CA_03_04','Calle 03 Seccion 04','03','04',0);

INSERT INTO UBICACIONES VALUES ('CA_03_05','Calle 03 Seccion 05','03','05',0);

INSERT INTO UBICACIONES VALUES ('CA_03_06','Calle 03 Seccion 06','03','06',0);

INSERT INTO UBICACIONES VALUES ('CA_03_07','Calle 03 Seccion 07','03','07',0);

INSERT INTO UBICACIONES VALUES ('CA_03_08','Calle 03 Seccion 08','03','08',0);

INSERT INTO UBICACIONES VALUES ('CA_03_09','Calle 03 Seccion 09','03','09',0);

INSERT INTO UBICACIONES VALUES ('CA_03_10','Calle 03 Seccion 10','03','10',0);

INSERT INTO UBICACIONES VALUES ('CA_03_11','Calle 03 Seccion 11','03','11',0);

INSERT INTO UBICACIONES VALUES ('CA_03_12','Calle 03 Seccion 12','03','12',0);

INSERT INTO UBICACIONES VALUES ('CA_03_13','Calle 03 Seccion 13','03','13',0);

-- CALLE 4

INSERT INTO UBICACIONES VALUES ('CA_04_01','Calle 04 Seccion 01','04','01',0);

INSERT INTO UBICACIONES VALUES ('CA_04_02','Calle 04 Seccion 02','04','02',0);

INSERT INTO UBICACIONES VALUES ('CA_04_03','Calle 04 Seccion 03','04','03',0);

INSERT INTO UBICACIONES VALUES ('CA_04_04','Calle 04 Seccion 04','04','04',0);

INSERT INTO UBICACIONES VALUES ('CA_04_05','Calle 04 Seccion 05','04','05',0);

INSERT INTO UBICACIONES VALUES ('CA_04_06','Calle 04 Seccion 06','04','06',0);

INSERT INTO UBICACIONES VALUES ('CA_04_07','Calle 04 Seccion 07','04','07',0);

INSERT INTO UBICACIONES VALUES ('CA_04_08','Calle 04 Seccion 08','04','08',0);

INSERT INTO UBICACIONES VALUES ('CA_04_09','Calle 04 Seccion 09','04','09',0);

INSERT INTO UBICACIONES VALUES ('CA_04_10','Calle 04 Seccion 10','04','10',0);

INSERT INTO UBICACIONES VALUES ('CA_04_11','Calle 04 Seccion 11','04','11',0);

INSERT INTO UBICACIONES VALUES ('CA_04_12','Calle 04 Seccion 12','04','12',0);

INSERT INTO UBICACIONES VALUES ('CA_04_13','Calle 04 Seccion 13','04','13',0);

-- CALLE 5

INSERT INTO UBICACIONES VALUES ('CA_05_01','Calle 05 Seccion 01','05','01',0);

INSERT INTO UBICACIONES VALUES ('CA_05_02','Calle 05 Seccion 02','05','02',0);

INSERT INTO UBICACIONES VALUES ('CA_05_03','Calle 05 Seccion 03','05','03',0);

INSERT INTO UBICACIONES VALUES ('CA_05_04','Calle 05 Seccion 04','05','04',0);

INSERT INTO UBICACIONES VALUES ('CA_05_05','Calle 05 Seccion 05','05','05',0);

INSERT INTO UBICACIONES VALUES ('CA_05_06','Calle 05 Seccion 06','05','06',0);

INSERT INTO UBICACIONES VALUES ('CA_05_07','Calle 05 Seccion 07','05','07',0);

INSERT INTO UBICACIONES VALUES ('CA_05_08','Calle 05 Seccion 08','05','08',0);

INSERT INTO UBICACIONES VALUES ('CA_05_09','Calle 05 Seccion 09','05','09',0);

INSERT INTO UBICACIONES VALUES ('CA_05_10','Calle 05 Seccion 10','05','10',0);

INSERT INTO UBICACIONES VALUES ('CA_05_11','Calle 05 Seccion 11','05','11',0);

INSERT INTO UBICACIONES VALUES ('CA_05_12','Calle 05 Seccion 12','05','12',0);

INSERT INTO UBICACIONES VALUES ('CA_05_13','Calle 05 Seccion 13','05','13',0);

---------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------Cambios---------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------





