ALTER VIEW V_MOVIMIENTOS_PICKING AS
SELECT COD_MOVIMIENTO, COD_PETICION, MOV.COD_PALET, PAL.COD_REFERENCIA, REF.DES_REFERENCIA, PAL.UBICACION
 
FROM MOVIMIENTOS_PICKING MOV
LEFT JOIN PALETS PAL
ON PAL.COD_PALET = MOV.COD_PALET

LEFT JOIN V_REFERENCIAS REF
ON REF.COD_REFERENCIA = PAL.COD_REFERENCIA;