ALTER VIEW V_ORDEN_SALIDA_LIN AS
SELECT COD_PETICION, COD_LINEA, ORDEN_SALIDA_LIN.COD_REFERENCIA, REFERENCIAS.DES_REFERENCIA, CANTIDAD, REFERENCIAS.PRECIO , STOCK
 
FROM ORDEN_SALIDA_LIN
LEFT JOIN REFERENCIAS
ON ORDEN_SALIDA_LIN.COD_REFERENCIA = REFERENCIAS.COD_REFERENCIA

LEFT JOIN V_REFERENCIAS
ON V_REFERENCIAS.COD_REFERENCIA = ORDEN_SALIDA_LIN.COD_REFERENCIA;