ALTER VIEW V_ORDEN_SALIDA_CAB AS

SELECT COD_PETICION, ESTADO, DES_ESTADO, ORDEN_SALIDA_CAB.ID_EMPRESA, DES_EMPRESA, DIRECCION_ENTREGA, COD_POSTAL, POBLACION, PROVINCIA, TELEFONO, FECH_CREACION,

(SELECT COUNT(*)
FROM ORDEN_SALIDA_LIN
WHERE ORDEN_SALIDA_CAB.COD_PETICION = ORDEN_SALIDA_LIN.COD_PETICION) AS CANTIDAD_LINEAS

FROM ORDEN_SALIDA_CAB
LEFT JOIN ESTADOS_ORDEN_SALIDA
ON ESTADO = COD_ESTADO
LEFT JOIN EMPRESAS
ON ORDEN_SALIDA_CAB.ID_EMPRESA = EMPRESAS.ID_EMPRESA;