ALTER VIEW V_ORDEN_SALIDA_INCIDENCIAS AS
SELECT INC.ID_INCIDENCIA, INC.DES_INCIDENCIA, CAB.ESTADO, INC.COD_PETICION, CAB.ID_EMPRESA, CAB.DIRECCION_ENTREGA, CAB.COD_POSTAL, CAB.POBLACION
 
FROM ORDEN_SALIDA_INCIDENCIAS INC

left JOIN ORDEN_SALIDA_CAB CAB
ON INC.COD_PETICION = CAB.COD_PETICION









