ALTER VIEW V_RECEPCIONES_LIN AS
SELECT ALBARAN, COD_LINEA, RECEPCIONES_LIN.COD_REFERENCIA, REFERENCIAS.DES_REFERENCIA, CANTIDAD, REFERENCIAS.PRECIO , STOCK
 
FROM RECEPCIONES_LIN
LEFT JOIN REFERENCIAS
ON RECEPCIONES_LIN.COD_REFERENCIA = REFERENCIAS.COD_REFERENCIA

LEFT JOIN V_REFERENCIAS
ON V_REFERENCIAS.COD_REFERENCIA = RECEPCIONES_LIN.COD_REFERENCIA;