ALTER VIEW V_RECEPCIONES_CAB AS

SELECT ALBARAN, ESTADO, DES_ESTADO, PROVEEDOR, FECH_CREACION, FECH_LLEGADA,

(SELECT COUNT(*)
FROM RECEPCIONES_LIN
WHERE RECEPCIONES_CAB.ALBARAN = RECEPCIONES_LIN.ALBARAN) AS CANTIDAD_LINEAS

FROM RECEPCIONES_CAB
LEFT JOIN ESTADOS_RECEPCION
ON ESTADO = COD_ESTADO;